name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN}}
        
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      
        
    - name: verify
      run: echo ${{steps.docker_build.ouput.digest}}
      
