name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: "build and push image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Build and push image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{steps.buildx.ouput.name}}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/node-app
      - name: verify
        run: echo ${{steps.docker_build.ouput.digest}}
  deploy:
    name: "Update server"
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Get commit revision
        id: vars
        shell: bash
        run: echo ::set-output name=tag::$(echo $(git describe --long --tags --always)| sed 's/v//')

      - name: SSH and deploy in server
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PORT: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ env.PROJECT_PATH }}
            docker-compose up -d
